### ISSUE TITLE
Why not a custom target?

### ISSUE THREAD

**Issue by KubaO** [sauter-hq/cmake-ide-support#1]
A custom target would not attempt to generate an executable, and has been supported since CMake 2.6: https://cmake.org/cmake/help/cmake2.6docs.html#command:add_custom_target

> The `SOURCES` option specifies additional source files to be included in the custom target. Specified source files will be added to IDE project files for convenience in editing even if they have not build rules.

**Comment by daminetreg** [comment]
Hi @KubaO,

Thanks for your feedback. I think it’s a real target because it didn’t work properly in QtCreator and my remembering is that autocomplete inside headers file was not done, finding function references etc.

Because the custom target doesn’t share all the target_include_directories, add_definitions etc. Which allow proper completion.

But if you can show me wrong, I’m happy to accept a PR.

**Comment by daminetreg** [comment]
Closing as no more activity for a month.
